// Generated by Recall (install.py --opencode). Do not edit — re-run the
// installer to update, or delete this file to disconnect Recall from opencode.
//
// Bridges opencode's plugin events to Recall's local Python scripts: on every
// session.idle (opencode's "turn finished" signal), new activity is appended
// to .recall/history.md by opencode_capture.py. Fully local — the script makes
// no network calls, and failures are swallowed so a session is never affected.
// https://github.com/raiyanyahya/recall

const SCRIPTS = "__RECALL_SCRIPTS__"

export const Recall = async ({ directory, $ }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return
      const sessionID = event.properties && event.properties.sessionID
      if (!sessionID) return
      const capture = `${SCRIPTS}/opencode_capture.py`
      // python3 with a plain-`python` fallback (Windows installs python.exe only)
      const r = await $`python3 ${capture} --cwd ${directory} --session ${sessionID}`
        .quiet()
        .nothrow()
      if (r.exitCode !== 0) {
        await $`python ${capture} --cwd ${directory} --session ${sessionID}`
          .quiet()
          .nothrow()
      }
    },
  }
}
