#!/usr/bin/env python3
"""Flag-based installer for Recall's optional harness integrations.

Claude Code needs NO install step — the plugin marketplace handles it — and
nothing this script does is required for (or can affect) the Claude Code path.

``--opencode`` wires Recall into an opencode project, explicitly and
reversibly:

    python3 scripts/install.py --opencode [--project DIR]

It writes exactly three things, all inside the target project:

  1. ``.opencode/plugins/recall.ts``        — capture shim: on every
     session.idle, append new activity to .recall/history.md
  2. ``.opencode/commands/recall-save.md``  — the /recall-save command
  3. ``opencode.json``                      — adds ".recall/context.md" to
     ``instructions`` so the saved context loads at session start

``--uninstall`` removes 1 and 2 and the instructions entry. A file that this
installer did not generate (no "Generated by Recall" marker) is never
overwritten or deleted. Stdlib-only.
"""

import argparse
import json
import os
import sys
from pathlib import Path

MARKER = "Generated by Recall"
CONTEXT_INSTRUCTION = ".recall/context.md"

SCRIPTS_DIR = Path(__file__).resolve().parent
TEMPLATES = SCRIPTS_DIR.parent / "integrations" / "opencode"

# (template relative to TEMPLATES, destination relative to the project root)
_GENERATED = [
    ("recall.ts", Path(".opencode") / "plugins" / "recall.ts"),
    (str(Path("commands") / "recall-save.md"),
     Path(".opencode") / "commands" / "recall-save.md"),
]


def _render(template_rel):
    text = (TEMPLATES / template_rel).read_text(encoding="utf-8")
    # as_posix() so the embedded path is valid inside a TS string on Windows too
    return text.replace("__RECALL_SCRIPTS__", SCRIPTS_DIR.as_posix())


def _write_generated(dest, content):
    """Write dest, refusing to clobber a file we didn't generate."""
    if dest.exists():
        existing = dest.read_text(encoding="utf-8", errors="replace")
        if MARKER not in existing:
            print(f"  SKIP  {dest} — exists and was not generated by Recall; "
                  "not overwriting.")
            return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    print(f"  wrote {dest}")
    return True


def _remove_generated(dest):
    """Delete dest only if this installer generated it."""
    if not dest.exists():
        return True
    if MARKER not in dest.read_text(encoding="utf-8", errors="replace"):
        print(f"  SKIP  {dest} — was not generated by Recall; not deleting.")
        return False
    dest.unlink()
    print(f"  removed {dest}")
    return True


def _update_opencode_json(root, add):
    """Add/remove the context.md instructions entry, preserving everything else.
    A config we can't parse is left untouched — never break a user's setup."""
    path = root / "opencode.json"
    cfg = {"$schema": "https://opencode.ai/config.json"}
    if path.exists():
        try:
            cfg = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            print(f"  SKIP  {path} — could not parse it; "
                  f"{'add' if add else 'remove'} \"{CONTEXT_INSTRUCTION}\" "
                  'in "instructions" manually.')
            return False
        if not isinstance(cfg, dict):
            print(f"  SKIP  {path} — unexpected top-level shape; edit manually.")
            return False

    instructions = cfg.get("instructions")
    if not isinstance(instructions, list):
        instructions = []

    if add:
        if CONTEXT_INSTRUCTION in instructions:
            print(f"  ok    {path} already lists \"{CONTEXT_INSTRUCTION}\"")
            return True
        instructions = instructions + [CONTEXT_INSTRUCTION]
    else:
        if CONTEXT_INSTRUCTION not in instructions:
            return True
        instructions = [i for i in instructions if i != CONTEXT_INSTRUCTION]

    if instructions:
        cfg["instructions"] = instructions
    else:
        cfg.pop("instructions", None)
    path.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {path}")
    return True


def install_opencode(root):
    print(f"Installing Recall's opencode integration into {root}\n")
    ok = True
    for template_rel, dest_rel in _GENERATED:
        ok = _write_generated(root / dest_rel, _render(template_rel)) and ok
    ok = _update_opencode_json(root, add=True) and ok
    print(
        "\nDone. What to expect in this project:\n"
        "  - every opencode turn appends new activity to .recall/history.md\n"
        "  - /recall-save regenerates .recall/context.md with the local summarizer\n"
        "  - opencode loads .recall/context.md at session start (via `instructions`)\n"
        "\nNotes:\n"
        "  - the plugin points at this Recall checkout "
        f"({SCRIPTS_DIR.as_posix()}); keep it in place, and re-run the\n"
        "    installer if you move it\n"
        "  - python3 (or python) must be on opencode's PATH\n"
        "  - opencode loads context.md as instructions, without Claude Code's\n"
        "    untrusted-data fencing — if .recall/ is committed and shared, only\n"
        "    do so with collaborators you trust (see README)\n"
        "  - your Claude Code installation of Recall is unaffected\n"
        "\nUninstall anytime: python3 scripts/install.py --opencode --uninstall "
        f"--project {root}"
    )
    return 0 if ok else 1


def uninstall_opencode(root):
    print(f"Removing Recall's opencode integration from {root}\n")
    ok = True
    for _template_rel, dest_rel in _GENERATED:
        ok = _remove_generated(root / dest_rel) and ok
    ok = _update_opencode_json(root, add=False) and ok
    print("\nDone. Your .recall/ data (history.md, context.md) was left in place.")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(
        description="Install Recall's optional integrations (Claude Code needs "
                    "no install step — this is only for other harnesses).")
    ap.add_argument("--opencode", action="store_true",
                    help="wire Recall into an opencode project")
    ap.add_argument("--project", default=os.getcwd(),
                    help="target project root (default: current directory)")
    ap.add_argument("--uninstall", action="store_true",
                    help="remove a previous --opencode install from the project")
    args = ap.parse_args()

    if not args.opencode:
        ap.error("nothing to do: pass --opencode "
                 "(the Claude Code plugin needs no install step)")
    root = Path(args.project).resolve()
    if not root.is_dir():
        ap.error(f"--project {root} is not a directory")
    sys.exit(uninstall_opencode(root) if args.uninstall else install_opencode(root))


if __name__ == "__main__":
    main()
